feat(conventional-changelog-writer): support async `options.transform` and `options.finalizeContext` #471
conventional-changelog/conventional-changelog pull request #1065
Opened 2023-07-15 12:44 UTC by 1aron

Now you can return promises in `transform` and `finalizeContenxt`:
```js
export default {
    async transform: (commit, context) => {
        return await ...
    },
    async finalizeContext: (context, options, commits) => {
        return await ...
    }
}
```

2023-08-05 23:33 UTC, dangreen requested changes
Hi. Thank you for the PR. Please rebase to current master.

2023-08-15 17:05 UTC, dangreen requested changes
Please add test cases for async transform and finalizeContext

2023-08-15 17:05 UTC, dangreen commented on packages/conventional-changelog-writer/test/index.spec.js
> +        const changelog = await await conventionalChangelogWriter.parseArray(commits, {
typo

2023-08-15 17:05 UTC, dangreen commented on packages/conventional-changelog-writer/test/index.spec.js
> +      const changelog = await await conventionalChangelogWriter.parseArray(commits, {
typo

2023-08-15 17:42 UTC, 1aron commented
> Please add test cases for async transform and finalizeContext

The previous changes were a bit rough 😅 and have been improved.

2023-08-26 13:05 UTC, dangreen approved these changes

2023-08-26 13:10 UTC, merged