fix: add possibility to provide custom flags to commit fetcher
conventional-changelog/conventional-changelog pull request #978
Opened 2023-04-16 16:50 UTC by cakeinpanic

Providing a way to bypass this issue
 https://github.com/conventional-changelog/conventional-changelog/issues/924

2023-04-17 08:16 UTC, cakeinpanic commented
@dangreen please take a look at this small change, it's minor non-breaking release which would unblock me a loooot :)

2023-04-17 09:23 UTC, dangreen requested changes
Hi. Thank you for the contribution. 

Could you please run `pnpm fix` to lint and fix possible lint issues?

2023-04-17 09:23 UTC, dangreen commented on packages/conventional-recommended-bump/index.js
> +  const options = Object.assign({ ignoreReverted: true, gitRawCommitsOpts:{} }, optionsArgument)
```suggestion
  const options = Object.assign({
    ignoreReverted: true,
    gitRawCommitsOpts: {}
  }, optionsArgument)
```

2023-04-17 11:44 UTC, cakeinpanic commented on packages/conventional-recommended-bump/index.js
> +  const options = Object.assign({ ignoreReverted: true, gitRawCommitsOpts:{} }, optionsArgument)
done

2023-04-19 13:34 UTC, cakeinpanic commented
@dangreen please take a look now

2023-04-19 18:12 UTC, merged

2023-05-10 10:36 UTC, dangreen commented
@bcoe Hello. Could you help with the release? What steps should we take?

2023-06-06 23:03 UTC, dangreen commented
@cakeinpanic Released